apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
  namespace: root-demo
  labels:
    configsync.playground/sync: rootsync
spec:
  podSelector: {}
  policyTypes:
    - Ingress
