apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: root-demo-configmap-reader
  labels:
    configsync.playground/sync: rootsync
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
